"""Monthly RANGE partitions for track_points (PostgreSQL only).

Revision ID: 003_track_parts
Revises: 002_track_idx
Create Date: 2026-08-20
"""

from __future__ import annotations

from datetime import date
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.services.tracks import add_months, month_start, partition_name

revision: str = "003_track_parts"
down_revision: Union[str, None] = "002_track_idx"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    kind = bind.execute(
        sa.text(
            """
            SELECT c.relkind
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = 'public' AND c.relname = 'track_points'
            """
        )
    ).scalar()
    if kind is None or kind == "p":
        return

    op.execute(sa.text("ALTER TABLE track_points RENAME TO track_points_old"))
    op.execute(
        sa.text(
            """
            CREATE TABLE track_points (
                id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                vehicle_id INTEGER NOT NULL REFERENCES vehicles(id),
                lat DOUBLE PRECISION NOT NULL,
                lon DOUBLE PRECISION NOT NULL,
                source VARCHAR(16) NOT NULL DEFAULT 'sim',
                ts TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
                PRIMARY KEY (id, ts)
            ) PARTITION BY RANGE (ts)
            """
        )
    )

    start = date(2025, 1, 1)
    last = add_months(month_start(date.today()), 12)
    cur = start
    while cur < last:
        nxt = add_months(cur, 1)
        name = partition_name(cur)
        op.execute(
            sa.text(
                f'CREATE TABLE IF NOT EXISTS "{name}" PARTITION OF track_points '
                f"FOR VALUES FROM ('{cur.isoformat()}') TO ('{nxt.isoformat()}')"
            )
        )
        cur = nxt

    op.execute(
        sa.text(
            """
            INSERT INTO track_points (id, vehicle_id, lat, lon, source, ts)
            SELECT id, vehicle_id, lat, lon, source, ts FROM track_points_old
            """
        )
    )
    op.execute(
        sa.text(
            """
            SELECT setval(
                pg_get_serial_sequence('track_points', 'id'),
                GREATEST((SELECT COALESCE(MAX(id), 1) FROM track_points), 1)
            )
            """
        )
    )
    op.execute(sa.text("DROP TABLE track_points_old"))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_track_points_vehicle_ts ON track_points (vehicle_id, ts)"))


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    kind = bind.execute(
        sa.text(
            """
            SELECT c.relkind
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = 'public' AND c.relname = 'track_points'
            """
        )
    ).scalar()
    if kind != "p":
        return
    op.execute(
        sa.text(
            """
            CREATE TABLE track_points_plain (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                vehicle_id INTEGER NOT NULL REFERENCES vehicles(id),
                lat DOUBLE PRECISION NOT NULL,
                lon DOUBLE PRECISION NOT NULL,
                source VARCHAR(16) NOT NULL DEFAULT 'sim',
                ts TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            INSERT INTO track_points_plain (id, vehicle_id, lat, lon, source, ts)
            SELECT id, vehicle_id, lat, lon, source, ts FROM track_points
            """
        )
    )
    op.execute(sa.text("DROP TABLE track_points CASCADE"))
    op.execute(sa.text("ALTER TABLE track_points_plain RENAME TO track_points"))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_track_points_vehicle_ts ON track_points (vehicle_id, ts)"))
